import { getServerSession } from 'next-auth'
import './styles/global.scss'
import { authOptions } from './api/auth/[...nextauth]/route'
import Login from '@/Components/Client/Login'
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css"
import Header from '@/Components/Server/Header'

export const metadata = {
  title: 'Rank Tracker',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        {!session && (
          <Login />
        )}
        {session && (
          <>
            <Header />
            {children}
          </>
        )}
      </body>
    </html>
  )
}
